DawnbrandBots/bastion-bot

src/metrics.ts
=> Allow guild field in metrics database to be NULL

package.json, src/commands/deck.ts, src/commands/index.ts, yarn.lock
Closes #12 
To be complete, will need database connection to fetch card names. Also needs a user-readable error message for YDKE failures.
=> Add deck printout command

src/commands/deck.ts
=> deck: Update stacked parameter description

.github/workflows/docker.yml, .github/workflows/release-compose.yml, .github/workflows/release-swarm.yml, docker-compose.yaml, docker-staging.yaml
The tests are not going to test the deploy step
=> Configure SEARCH_API environment variable in Docker

.github/workflows/node.js.yml, package.json, src/Command.ts, src/commands/deck.ts, src/commands/index.ts, src/commands/link.ts, src/commands/ping.ts, src/commands/yugipedia.ts, src/events/interaction.ts, yarn.lock
May resolve cryptic crashes we experienced
pls to ignore the wrong version number in the branch tag oops
=> Bump discord.js version

src/commands/deck.ts
If a deck printout goes over the character limit for an embed field, it's split over as many additional fields as needed.
=> Add overflow handling to deck command

src/utils.ts
Emoji do not render if hyperlinked on mobile
=> Don't hyperlink emoji for mobile

docs/commands/search.md
Document current behaviour and the rough roadmap for the feature
=> docs: /search

docs/commands/deck.md
=> docs: /deck [ci skip]

docs/commands/id.md
=> docs: /id [ci skip]

package.json, yarn.lock
Tooling upgrades that should have been done a while ago + discord.js 13.6 are the major ones
=> Rollup of dependency upgrades

docker-compose.yaml, docs/commands/locale.md, src/commands/index.ts, src/commands/locale.ts, src/index.ts, src/locale.ts
=> Add /locale command

src/logger.ts
https://discord.com/developers/docs/resources/channel#allowed-mentions-object
Apparently this file wasn't formatted with tabs; the only real change is the addition is on line 17.
=> Disable all mentions from logger webhook

docs/commands/art.md, src/card.ts, src/commands/art.ts, src/commands/id.ts, src/commands/index.ts, src/commands/search.ts
Displays the art of a specified card
There is some iteration to potentially be done on how we display this, error message included.
=> Add /art command

Dockerfile, docs/translations.md, package.json, src/commands/art.ts, src/index.ts, translations/README.md, translations/zh-CN.po, translations/zh-TW.po, yarn.lock
=> Add gettext-like localization system: ttag

src/commands/help.ts, src/commands/index.ts, translations/ko.po, translations/pt.po, translations/zh-CN.po, translations/zh-TW.po
Directs users to GitHub documentation for Slash Commands
=> Add "help" Slash Command

translations/pt.po
Including the translation to Brazilian Portuguese (PT-br)
=> Add translation to Brazilian Portuguese (PT-br)

package.json, src/Command.ts, src/bot.ts, src/card.ts, src/commands/art.ts, src/commands/deck.ts, src/commands/help.ts, src/commands/id.ts, src/commands/index.ts, src/commands/link.ts, src/commands/locale.ts, src/commands/ping.ts, src/commands/price.ts, src/commands/random.ts, src/commands/search.ts, src/commands/ygoprodeck.ts, src/commands/yugipedia.ts, src/events/interaction.ts, src/events/message.ts, src/locale.ts, src/metrics.ts, src/utils.ts, yarn.lock
=> Bump discord.js from 13.11.0 to 14.4.0

src/bot.ts, src/events/index.ts, src/events/message-delete.ts, src/events/message-search.ts, src/index.ts, src/message-cache.ts, test/message-cache.spec.ts
=> Implement delete listener for <> card search

src/abdeploy.ts, src/events/message-search.ts
Will need to time this deployment after the hour to convert the config
=> Invert ABDeploy to exclusion system

README.md, docs/card-search.md
Preview: 
https://github.com/DawnbrandBots/bastion-bot/tree/docs-new-search#readme
https://github.com/DawnbrandBots/bastion-bot/blob/docs-new-search/docs/card-search.md
and proofread!
=> docs: new search experience [ci skip]

src/bot.ts, src/events/message-search.ts, src/locale.ts, translations/de.po, translations/es.po, translations/fr.po, translations/it.po, translations/ja.po, translations/ko.po, translations/pt.po, translations/zh-CN.po, translations/zh-TW.po
=> Add search language and type to <> card search no-match messages

src/events/message-ping.ts, src/events/message-search.ts, src/metrics.ts, translations/de.po, translations/es.po, translations/fr.po, translations/it.po, translations/ja.po, translations/ko.po, translations/pt.po, translations/zh-CN.po, translations/zh-TW.po
The main hyperlink is to the triggering message.
Closes #186
=> Send a warning to direct messages if missing permissions

src/events/message-ping.ts, src/events/message-search.ts
System messages cannot be replied to and are unlikely to be intentional searches
Closes #187
=> Ignore system messages for message events

src/commands/price.ts
=> Localise price output

src/commands/deck.ts, src/commands/rush-duel.ts, translations/de.po, translations/es.po, translations/fr.po, translations/it.po, translations/ja.po, translations/ko.po, translations/pt.po, translations/zh-CN.po, translations/zh-TW.po
Comes with an art switcher/gallery/carousel
Closes #228
=> Add /rush-duel art subcommand

.github/workflows/node.js.yml, Dockerfile, package.json, src/Command.ts, src/bot.ts, src/utils.ts, test/events/message-ping.spec.ts, yarn.lock
~typescript-tooling's essentials also would need to be bumped~ done
=> Bump Node.js to v18, TypeScript to 4.9

src/index.ts, src/locale.ts, test/locale.spec.ts
=> Add unit tests for .po files

src/events/message-search.ts
Following the approach in #272, for `<>` message search, which have been timing out without response after 2.5 s more and more often lately, add a retry policy. Shorten the timeout to half a second and retry 4 times as soon as possible. Note that half a second is often too long for local testing, but for the production server, which is co-located, anything taking longer than this is probably OpenSearch hanging and will never get a reply in a reasonable time.
If this looks good, please merge and deploy!
=> Aggressively retry to work around search timeouts

src/commands/deck.ts, src/commands/random.ts, src/events/message-search.ts
- message search: 2.5 s timeout, default got retries (wait 1 s, retry, wait 2 s, retry, fail)
- /random: ditto
- /deck: 5 s timeout
#272 
Will see how this performs this week and how the unchanged /art and /search compare.
=> Update some timeout and retry mechanisms

src/card.ts, src/commands/random.ts, src/commands/rush-duel.ts, src/commands/search.ts, src/events/message-search.ts, src/index.ts, src/limit-regulation.ts
=> Display Rush Duel and Master Duel limit regulations

.github/workflows/node.js.yml
=> Added ESLint result uploading to Compile and test workflow

.github/workflows/node.js.integration.yml, .vscode/launch.json, package.json, test/integration/message-search.test.ts
=> Add integration tests using Singing Lanius

src/events/message-search.ts, src/index.ts, src/metrics.ts
=> Extend <> message card search to Rush Duel

package.json, yarn.lock
=> Remove resolution for undici and make-dir

README.md, translations/README.de.md, translations/README.es.md, translations/README.fr.md, translations/README.it.md, translations/README.ja.md, translations/README.ko.md, translations/README.md, translations/README.pt.md, translations/README.zh-CN.md, translations/README.zh-TW.md
Preview properly at https://github.com/DawnbrandBots/bastion-bot/tree/i18n-readme#readme
=> Add links and placeholders for localized READMEs [ci skip]

package.json, src/events/message-delete.ts, src/events/message-search.ts, test/integration/message-search.test.ts, test/unit/events/message-ping.spec.ts, yarn.lock
=> Bump discord.js to 14.16.1

.github/workflows/docker.yml, src/commands/art.ts, src/commands/deck.ts, src/commands/help.ts, src/commands/id.ts, src/commands/index.ts, src/commands/link.ts, src/commands/metagame.ts, src/commands/ping.ts, src/commands/price.ts, src/commands/query.ts, src/commands/random.ts, src/commands/rush-duel.ts, src/commands/search.ts, src/commands/ygoprodeck.ts, src/commands/yugipedia.ts, src/locale.ts
=> Enable all commands except /locale for user installation in preview

.github/workflows/docker.yml, .github/workflows/release-compose.yml, docker-compose.yaml, docker-staging.yaml, package.json, src/commands/deck.ts, yarn.lock
=> Remove FTP integration with YGOPRODECK

translations/ja.po
Here's some updates! The original were nice guesses 🆒
=> Update ja.po for /yugipedia
