DawnbrandBots/bastion-bot

src/metrics.ts

Fix #10 
We were joining an array of objects, we now map those objects to strings first.
The format of the string we record is up for discussion. The initial implementation was a simple, human-readable option but something like JSON may be preferable for comprehensiveness and program-readability.

Fix argument serialisation in metrics

---

src/commands/deck.ts

Uses new optional "public" parameter with default false to determine whether or not to use an ephemeral reply.
This option has arguable applicability to almost any command, but is particularly well-suited to deck profiles because they can be shared or kept private, and can clog the chat.

Add option to show deck profile publicly

---

src/commands/deck.ts

Adds counts of Main and Extra deck categories to the section headers.
Adds the option to view sections as side-by-side columns.
Includes adaptations for updates to the API
A bunch of janky lambdas here to avoid code duplication between main/extra/side. This might not be it, chief.

deck: Add new UI flourishes

---

package.json
yarn.lock

@discordjs/builders is also a dependency of discord.js that gets bumped every time. Since we're using yarn, let's rely on the transitive dependency instead of having to remember to bump both.

Bump discord.js to 13.5

---

src/commands/deck.ts
src/commands/id.ts
src/commands/index.ts

Close #23.
The name need not be final, we no longer call passwords `ids` and it could be confused with the `kid`, but we *can* justify the name by saying it identifies cards?
Inference of the input type is not implemented yet.

Add /id command

---

docs/commands/search.md
src/commands/deck.ts
src/commands/id.ts
src/commands/link.ts
src/commands/ping.ts
src/commands/search.ts
src/commands/ygoprodeck.ts
src/commands/yugipedia.ts
src/utils.ts

Promise.any or Promise.race may be useful to defer/initial reply and send the API request simultaneously

Improve latency calculations and never inadvertently fail a command due to network delays

---

docs/commands/search.md
src/commands/locale.ts
src/commands/search.ts
src/locale.ts

Now we'll make use of the `/locale` setting or the Discord-provided locale.
Convert LocaleProvider to abstract class and move convenience methods in
For #47

/search: use LocaleProvider and make lang parameter optional

---

docs/commands/deck.md
package.json
src/commands/deck.ts
translations/de.po
translations/es.po
translations/fr.po
translations/it.po
translations/ja.po
translations/ko.po
translations/pt.po
translations/zh-CN.po
translations/zh-TW.po
yarn.lock

- Add .ydk file support by splitting into subcommands
- Output ydke:// URL and .ydk file of the submitted deck
- The name and description for the command and its options have localisation support
- Closes #22 
- I'm not sure what the process is for getting newly added text translated. This update adds new error messages, as well as the above-noted localisation support.
- Deck parsing is handled by the `ydeck` package, which has unlocalised and sometimes unclear error messages. More effort should be put in to intercept them and present them in a localised and user-friendly manner.
- Uploaded files are currently checked against guards for extension and file-size - these are based on Emcee's behaviour, but ultimately arbitrary, and we could choose to revise them before merging this PR.

/deck: support YDK files

---

src/commands/deck.ts
src/commands/index.ts
src/commands/price.ts
src/utils.ts
translations/de.po
translations/es.po
translations/fr.po
translations/it.po
translations/ja.po
translations/ko.po
translations/pt.po
translations/zh-CN.po
translations/zh-TW.po

Ported from https://github.com/AlphaKretin/ygoprodeck-tag-bot/blob/master/modules/price.ts
Closes #140.

Add /price command

---

src/card.ts
translations/de.po
translations/es.po
translations/fr.po
translations/it.po
translations/ja.po
translations/ko.po
translations/pt.po
translations/zh-CN.po
translations/zh-TW.po

Closes #171 
It's not immediately clear if the URL should be left of the Official Konami ones, but I think this way makes sense.

Prioritise YGOPRODECK URLs for card embeds

---

package.json
src/bot.ts
src/events/index.ts
src/events/message-ping.ts
src/events/message-search.ts
src/index.ts
test/events/message-search.spec.ts
test/events/message.spec.ts
yarn.lock

- Ignores more markup (correctly) than old Bastion
- Will not trigger on Slash Command or timestamp mentions
- Delimiter overrides hardcoded for five servers
- Doubled delimiters for `<`, `[`, and `=` are still ignored
- Hyperlinks, "(", and "anime" are skipped
- Only the first three matches are searched, and the above don't count. This is a departure from too many attempted searches entirely rejecting
- Language overrides by trailing `,lang` and `,lang,lang` work, but a single language in card name mode does not change the result language from the current setting, only the input language
- Konami ID search supported by prefixing numeric query with `%`
- Reactions still added and removed if possible
#152 
https://github.com/AlphaKretin/bastion-bot/blob/master/modules/cardSearch.ts

Implement <> card search

---

src/events/message-search.ts

Do a cache permission check first to avoid the overhead of attempting to react (HTTP REST call).
Additionally send a typing indicator to indicate 🤔 ⏲️ 
Only log at warning level if the error on reacting was not missing permissions or being blocked by the requester.
Only log at warning level if the error on removal was not the message being deleted.
Closes #191

Improve logging behaviour for reactions

---

src/card.ts
translations/de.po
translations/es.po
translations/fr.po
translations/it.po
translations/ja.po
translations/ko.po
translations/pt.po
translations/zh-CN.po
translations/zh-TW.po

Open to feedback on what the footer should look like. This also fixes the instances of `Password: null` or `Konami ID #null` as that has unclear meaning to the layperson. However, "fake password" also isn't necessarily clear to the layperson either.

Display placeholder IDs in card embed footer

---

src/bot.ts

Given #199 and #204, this is an interim warning system before we can get a full healthcheck bot going with incident notifications to GitHub

Add early warning canary if no messageCreate events are received for one minute

---

src/events/message-search.ts

Allows searching of cards like "7", passwords and Konami IDs are at least four digits long
Closes #188

Treat numeric searches under 4 digits as names

---

src/card.ts
src/commands/art.ts
src/commands/price.ts
src/commands/search.ts
src/locale.ts

getInputLangStringOption: use buildLocalisedCommand 
Create helpers for name/password/konami-id subcommands
Add getCardSearchOptions for shared logic
Remove simultaneous calls to deferReply and getCard
Closes #270
Closes #271

Switch password and konami-id subcommands to integer options

---

src/commands/rush-duel.ts

As of writing, Yugipedia has 1312 images available vs 694 images, at a cost of one-quarter the resolution (512x512 vs 1024x1024). Closes #281

/rush-duel: update artwork to the second Rush Duel video game (G002)

---

src/card.ts
translations/de.po
translations/es.po
translations/fr.po
translations/it.po
translations/ja.po
translations/ko.po
translations/pt.po
translations/zh-CN.po
translations/zh-TW.po

Three days ago, Yugipedia updated Speed Duel cards to display the correct limit regulation for the format, i.e. `Limited 1`, `Limited 2`, `Limited 3`. DawnbrandBots/yaml-yugi@e2eb79bc0e17364cf96852c8c2a64d63cdbad863
This caused the strong typing of our API type definitions to break, and the API started returning 500 for cards on the Speed Duel Limited List. Popular examples include:
- Allure of Darkness: <https://github.com/DawnbrandBots/yaml-yugi/blob/a76469b8d343eca3d5428623fbaf3ff80148ec4f/data/cards/01475311.yaml#L4>
- Book of Moon: <https://github.com/DawnbrandBots/yaml-yugi/blob/a76469b8d343eca3d5428623fbaf3ff80148ec4f/data/cards/14087893.yaml#L4>
- Cosmic Cyclone: <https://github.com/DawnbrandBots/yaml-yugi/blob/a76469b8d343eca3d5428623fbaf3ff80148ec4f/data/cards/08267140.yaml#L4> …

Handle Speed Duel limit regulations

---

src/commands/index.ts
src/commands/query.ts

This is intended to succeed old Bastion [`.match` and `.search`](https://github.com/AlphaKretin/bastion-bot/wiki/Commands-for-users#finding-cards). [Lucene queries](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-query-string-query.html#query-string-syntax) are more powerful than the ygo-data filter system and require no additional implementation effort.
[Simple query strings](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-simple-query-string-query.html) are also possible for most search cases but are not implemented here as they cannot search on arbitrary fields. In context, only about 3% of `.match` and `.search` invocations applied additional filters on card properties rather than just searching text.

/query: create development/preview-only prototype

---

src/art.ts
src/card.ts
src/commands/art.ts
src/commands/rush-duel.ts
test/unit/__snapshots__/art.spec.ts.snap
test/unit/art.spec.ts
test/unit/card.spec.ts

/art no longer calls Yugipedia by assuming the Master Duel redirect exists if there is Master Duel rarity data.
/rush-duel art reduces calls to Yugipedia by skipping the redirect check when illustrations are already specified.
Rework some illustration URL construction logic to create a common yugipediaFileRedirect helper, with unit testing.
Add some unit tests for the ArtSwitcher.
Closes #443

/art, /rush-duel art: reduce calls to Yugipedia

---

src/events/message-ping.ts
src/utils.ts
test/unit/events/message-ping.spec.ts

Four months ago in #434 (1e121303f6229164f4f1fbbe43a3df4f0dbde316), a change was introduced that synchronized the ignore condition between the message ping and message search listeners. This added a new condition to ignore replies for message search. This behaviour is incorrect, unintuitive, and undocumented as all replies are ignored, not just direct replies, and there are no merits of ignoring even those for message search. This should fix most cases reported in #454, though there still remain uncommon cases of Discord not sending the message event. This also updates the logic in PingMessageListener so it can safely handle replies to other users containing a mention while ignoring reply mentions.

Fix replies being ignored

---

src/card.ts
src/rush-duel.ts

Per https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline (and https://gist.github.com/matthewzring/9f7bbfd102003963f9be7dbcf7d40e51), adding `-# ` at the start of a line causes it to appear as subtext on Discord. The font size is smaller and the colour is muted. This is exclusively Discord-flavoured markdown and does not appear in other dialects.
We use this to render ruby text for Japanese and Korean when it's available. In these cases, the embed will not have a title. The description section instead starts with the constructed ruby text of the card name as a subtext, followed by the base text of the card name, bolded and hyperlinked as if it were still the embed title. Using a markdown header is not good here as we can't get rid …

Display ruby text using Discord markdown for subtext

---

src/commands/locale-user.ts
src/commands/locale.ts
src/locale.ts
test/unit/events/message-ping.spec.ts
translations/de.po
translations/es.po
translations/fr.po
translations/it.po
translations/ja.po
translations/ko.po
translations/pt.po
translations/zh-CN.po
translations/zh-TW.po

User-install and direct messages are governed by a user-specific table. The same setting applies to all of these contexts. This means that in a server without Bastion, using user-installed Bastion commands will use the user's locale, the same as their direct messages, including group chats. Very few users had a locale override configured for direct messages and those will be manually migrated to the new user-based table from the channel-based one.
Points of improvement:
- remove async/await from LocaleProvider entirely
- expose the new modular LocaleScope API instead of specific methods
- logic is reproduced in three locations: LocaleProvider, /locale, and /locale-user

Update locale logic

---

package.json
yarn.lock

Only used for ttag-cli web. Brings in a bunch of useless (dev) dependencies that Dependabot is flagging as security issues (which are not real security issues for dev dependencies).

Remove koa dependencies
